# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 00:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NameList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_pairing', models.DateTimeField(auto_now=True)),
                ('namelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='groupsort.NameList')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('forbidden_pairings', models.ManyToManyField(related_name='_person_forbidden_pairings_+', to='groupsort.Person')),
                ('namelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='groupsort.NameList')),
            ],
        ),
        migrations.AddField(
            model_name='pairing',
            name='people',
            field=models.ManyToManyField(related_name='pairings', to='groupsort.Person'),
        ),
        migrations.AddField(
            model_name='groupset',
            name='namelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupsets', to='groupsort.NameList'),
        ),
        migrations.AddField(
            model_name='groups',
            name='groupset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groupsort.GroupSet'),
        ),
        migrations.AddField(
            model_name='groups',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to='groupsort.Person'),
        ),
    ]
