# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsort', '0002_auto_20160921_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupset',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
