# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsort', '0003_groupset_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupset',
            name='repeats',
            field=models.IntegerField(default=1),
        ),
    ]
